SELECT
    V.ID_VOO,
    V.AEROPORTO_ORIGEM,
    V.AEROPORTO_DESTINO,
    V.HORARIO_SAIDA,
    V.HORARIO_CHEGADA,
    A.TIPO_AERONAVE,
    E.AEROPORTO_ESCALA,
    E.HORARIO_SAIDA_ESCALA,
    P.LOCALIZACAO AS POLTRONA_DISPONIVEL
FROM
    VOO V
INNER JOIN
    AERONAVE A ON V.ID_AERONAVE = A.ID_AERONAVE
INNER JOIN
    ESCALA E ON V.ID_VOO = E.ID_VOO
LEFT JOIN
    POLTRONA P ON V.ID_VOO = P.ID_VOO AND P.DISPONIVEL = 1
ORDER BY
    A.TIPO_AERONAVE;