SELECT
    VOO.ID_VOO,
    VOO.AEROPORTO_ORIGEM,
    VOO.AEROPORTO_DESTINO,
    VOO.HORARIO_SAIDA,
    VOO.HORARIO_CHEGADA,
    AERONAVE.TIPO_AERONAVE,
    ESCALA.AEROPORTO_ESCALA,
    ESCALA.HORARIO_SAIDA_ESCALA
FROM
    VOO
INNER JOIN
    AERONAVE ON VOO.ID_AERONAVE = AERONAVE.ID_AERONAVE
INNER JOIN
    ESCALA ON VOO.ID_VOO = ESCALA.ID_VOO;
